apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmapprec
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  webproxy: true
  env:
    - name: MQ_HOST_NAME
      value: b27apvl177.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC04
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMAPPREC
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443